# Port for local testing
server.port: 8087

server:
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: false

  compression:
    enabled: true
    min-response-size: 4096
    mime-types: application/json, application/ld+json, application/xml, text/html, text/xml, text/plain

# Don't auto-start jobs, we'll let the JobCmdLineStarter do this
spring:
  batch:
    job:
      enabled: false
