package eu.europeana.api.recommend.common.model;

import java.io.Serializable;
import java.util.Arrays;

/**
 * Set of vectors generated by Embeddings API and saved into Milvus
 *
 * @author Patrick Ehlert
 */
public class RecordVectors  implements Serializable {

    private static final long serialVersionUID = 5388995526375071859L;

    private String id; // required for serializing responses from Embeddings API
    private Double[] embedding;

    public RecordVectors() {
        // Default constructor, required for Jackson deserialization
    }

    public RecordVectors(String id, Double[] embedding) {
        this.id = id;
        this.embedding = embedding;
    }

    public String getId() {
        return id;
    }

    public Double[] getEmbedding() {
        return embedding;
    }

    @Override
    public String toString() {
        return "RecordVectors{" +
                "id='" + id + '\'' +
                ", embedding=" + Arrays.toString(embedding) +
                '}';
    }
}
