package eu.europeana.api.recommend.updater.model.embeddings;

import java.util.Arrays;

/**
 * Set of vectors generated by Embeddings API and saved into Milvus
 *
 * @author Patrick Ehlert
 */
public class RecordVectors {

    private String id;
    private Double[] embedding;

    public String getId() {
        return id;
    }

    public Double[] getEmbedding() {
        return embedding;
    }

    @Override
    public String toString() {
        return "RecordVectors{" +
                "id='" + id + '\'' +
                ", embedding=" + Arrays.toString(embedding) +
                '}';
    }
}
